### ISSUE TITLE
Order of output of DLP table

### ISSUE THREAD

**Issue by anirusharma** [GoogleCloudPlatform/dlp-dataflow-deidentification#3]
Lets say in my use case  - i have 100 columns and i only want to mask 2 columns . so  I decide to send only 2 columns to add in DLP handler and get results of 2 columns back. 

Let's sent 1000 records (2 columns). 

Does call to DLP table guarantee order. If I send 1000 records (2 columns) and scale it to max capability of DLP. Is it a guarantee to get returns in same order. (because need to stitch records of these 2 columns back to 1000 column record). If DLP preserves order then can loop through both lists based on order and merge them. Or do I need to take care of joining these based on some key (which I'll have to identify) if DLP call doesn't guarantee to preserve order.

**Comment by santhh** [comment]
@anirusharma Call to DLP API happens in par do so order I don't think is maintained.

**Comment by anirusharma** [comment]
@santhh : thanks for help !
