### ISSUE TITLE
Using deidentify template and inspect template in a regional location results in permission error

### ISSUE THREAD

**Issue by shaqian** [GoogleCloudPlatform/dlp-dataflow-deidentification#67]
We are trying to deploy all resources in a regional location (us-east1). We made the following changes so that deidentify template and inspect template are created in us-east1 instead of global.

1. dlp-demo-part-1-crypto-key.yaml
```bash
    args:  ['kms', 'keyrings', 'create', '${_KEY_RING_NAME}', '--location=us-east1']
...
    args: ['kms', 'keys', 'create' ,'${_KEY_NAME}', '--location=us-east1','--purpose=encryption','--keyring=${_KEY_RING_NAME}']
```

2. create-kek.sh
```bash
KEK_API="${API_ROOT_URL}/v1/projects/${PROJECT_ID}/locations/us-east1/keyRings/${KEY_RING_NAME}/cryptoKeys/${KEY_NAME}:encrypt"
```

3. create-df-template.sh
```bash
INSPECT_TEMPLATE_API="${DLP_API_ROOT_URL}/v2/projects/${PROJECT_ID}/locations/us-east1/inspectTemplates"
...
TEMPLATES_LAUNCH_API="${DF_API_ROOT_URL}/v1b3/projects/${PROJECT_ID}/locations/us-east1/templates:launch"
```

4. create-dlp-template.sh
```bash
DEID_TEMPLATE_API="${API_ROOT_URL}/v2/projects/${PROJECT_ID}/locations/us-east1/deidentifyTemplates"
INSPECT_TEMPLATE_API="${API_ROOT_URL}/v2/projects/${PROJECT_ID}/locations/us-east1/inspectTemplates"
```

The problem is if we submit the Dataflow job using these templates, the job will report permission error.
```bash
export DEID_TEMPLATE_NAME=projects/{PROJECT-ID}/locations/us-east1/deidentifyTemplates/{TEMPLATE-NAME}
export INSPECT_TEMPLATE_NAME=projects/{PROJECT-ID}/locations/us-east1/inspectTemplates/{TEMPLATE-NAME}

export JOB_ID=my-deid-job-us-east1
gcloud dataflow jobs run ${JOB_ID}  \
    --gcs-location gs://dataflow-templates-us-east1/latest/Stream_DLP_GCS_Text_to_BigQuery \
    --region ${REGION} \
    --parameters \    "inputFilePattern=gs://${DATA_STORAGE_BUCKET}/CCRecords_1564602825.csv,dlpProjectId=${PROJECT_ID},deidentifyTemplateName=${DEID_TEMPLATE_NAME},inspectTemplateName=${INSPECT_TEMPLATE_NAME},datasetName=deid_dataset,batchSize=500"
```

Error:
```log
2020-11-13 17:39:11.721 HKTError message from worker: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Not authorized to access requested inspect template.
2020-11-13 17:27:09.146 HKTError message from worker: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Not authorized to access requested deidentify template.
```

It seems the Dataflow template cannot work with deidentify template or inspect template in a regional location. (Global location works as expected.) 

Any input is appreciated. 

Thanks,
Qian

**Comment by santhh** [comment]
If you can take out location param (locations/us-east1) by default it will take the global one. It should work. I have a plan to include regional location param soon.

**Comment by shaqian** [comment]
Hi Masud, 

We can't use global as we have location constrains and are only able to deploy to us-east1. Appreciate it if you can include the location param and modify the template to support DLP in regional location. 

Thanks,
Qian

**Comment by dwilliams782** [comment]
I have a very similar issue trying to create an inspect job with a regional template:

```
details = "Not authorized to access requested inspect template."
```

I'm going to move the template into a global resource and try that, but I'm fairly sure this is the issue.

**Comment by santhh** [comment]
ok Let me have a look today.

**Comment by santhh** [comment]
I have create this branch. You can include location param in gradle run. 
https://github.com/GoogleCloudPlatform/dlp-dataflow-deidentification/tree/sec_blueprint_change
```
--DLPParent=projects/<project-id>/locations/us-central1"
```
By default if not passed, it will take from --project param and location will be global.
Hope it helps.

**Comment by santhh** [comment]
https://github.com/GoogleCloudPlatform/dlp-dataflow-deidentification/blob/8e20b99b3ce79303e5884fe475fe9009df3eedb7/src/main/java/com/google/swarm/tokenization/DLPTextToBigQueryStreamingV2PipelineOptions.java#L149

**Comment by tibk** [comment]
@santhh Are you planning on merging this on master ? We have the same issue and we can't use global localisation due to security restrictions.

Kindly,

Tk

**Comment by santhh** [comment]
This is merged in master. Let me know if it works.
