### ISSUE TITLE
Gradle build issue

### ISSUE THREAD

**Issue by prashant-arch** [GoogleCloudPlatform/dlp-dataflow-deidentification#90]
We are trying to reidentifiation dataflow job by executing below command:-

gradle run -DmainClass=com.google.swarm.tokenization.DLPTextToBigQueryStreamingV2 \
  -Pargs="\
  --region=${REGION} \
  --project=${PROJECT_ID} \
  --stagingLocation=gs://${DATAFLOW_TEMP_BUCKET}/staging \
  --tempLocation=gs://${DATAFLOW_TEMP_BUCKET}/temp \
  --maxNumWorkers=2 \
  --runner=DataflowRunner \
  --tableRef=${PROJECT_ID}:deid_dataset.CCRecords_1564602825 \
  --dataset=deid_dataset \
  --topic=projects/${PROJECT_ID}/topics/${TOPIC_ID} \
  --autoscalingAlgorithm=THROUGHPUT_BASED \
  --workerMachineType=n1-standard-2 \
  --deidentifyTemplateName=${REID_TEMPLATE_NAME} \
  --DLPMethod=REID \
  --keyRange=1024 \
  --queryPath=gs://${DATA_STORAGE_BUCKET}/reid_query.sql"

Attaching the screenshot of error:-

![e3f7a94d-2546-410d-b26c-623ed7c8bee6](https://user-images.githubusercontent.com/61928295/174980903-db505a03-0c30-4821-8ed1-7cd44ac1cd0c.jpg)
![2c7dd3f9-d159-400f-91f0-d1e1605a516d](https://user-images.githubusercontent.com/61928295/174980947-955d7a18-dbcf-40b7-8eca-616f0620c528.jpg)

**Comment by pbhandary-test** [comment]
facing the same issue.
hopefully this gets resolved soon

**Comment by almagor1986** [comment]
In case anyone faces this problem in the future.

In dependencies, please change: 
- `compile` to `implementation`
- `testCompile` to `testImplementation`

In addition, remove the lines:
-  `classpath "net.ltgt.gradle:gradle-apt-plugin:0.19"`
- `apply plugin: "net.ltgt.apt"`
- `jcenter()`

This should get the code running.

**Comment by KevinGG** [comment]
This should be:

Either use the older gradle version controlled in `gradlew` (best practice);

Or update the build file to conform to the `gradle` version used by the user.

Anyway, if the build file and `gradlew` are both upgraded, this [instruction](https://cloud.google.com/architecture/validating-de-identified-data-bigquery-re-identifying-pii-data#re-identifying_the_dataset_from_bigquery) should also reflect the usage of version controlled `gradlew` not arbitrary gradle.

**Comment by prashant-arch** [comment]
Issue Resolved

**Comment by pbhandary-test** [comment]
@almagor1986 solution worked for me & as @KevinGG suggested updating the build file to conform to the gradle version worked .
